# Generated by Django 3.0.5 on 2020-04-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shell', '0013_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='slug',
            field=models.SlugField(unique_for_date='created'),
        ),
    ]
